### ISSUE TITLE
Version conflicts

### ISSUE THREAD

**Issue by jeroenterheerdt** [keesschollaart81/CaseOnline.Azure.WebJobs.Extensions.Mqtt#2]
I tried following the instruction but end up with a lot of versioning conflicts, such as for Newtonsoft.Json. Could you maybe update the readme with sample `PackageReferences`?

**Comment by keesschollaart81** [comment]
Hi Jeroen, thanks!

Can you please provide me with some steps to reproduce? 
- [ ] Which Visual Studio version are you using?
- [ ] How does you .csproj currently look like?
- [ ] What is the exact output of your build/debug loggin?
- [ ] Did you try to build the example project or did you do a file>new>project yourself?

**Comment by jeroenterheerdt** [comment]
1. VS Code
2. `<PackageReference Include="CaseOnline.Azure.WebJobs.Extensions.Mqtt" Version="0.0.2-beta" />
    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="2.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="2.0.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="1.0.12" />`
3. `C:\dev\functionsmqtt\functionsmqtt.csproj : error NU1107: Version conflict detected for Microsoft.Azure.WebJobs. Reference the
package directly from the project to resolve this issue.
C:\dev\functionsmqtt\functionsmqtt.csproj : error NU1107:  functionsmqtt -> CaseOnline.Azure.WebJobs.Extensions.Mqtt 0.0.2-beta -> Microsoft.Azure.WebJobs.Extensions 3.0.0-beta5 -> Microsoft.Azure.WebJobs (>= 3.0.0-beta5)
C:\dev\functionsmqtt\functionsmqtt.csproj : error NU1107:  functionsmqtt -> Microsoft.NET.Sdk.Functions 1.0.12 -> Microsoft.Azure.WebJobs (>= 2.2.0 && < 2.3.0).`
4. New project.

**Comment by keesschollaart81** [comment]
I tried it using new project in VS code on Mac and on Windows with these PackageReferences and it just works, so...

I think it's because of this ```Microsoft.NET.Sdk.Functions 1.0.12 -> Microsoft.Azure.WebJobs (>= 2.2.0 && < 2.3.0)``` part of the log you posted. The 1.0.12 version of Microsoft.NET.Sdk.Functions only depends on Microsoft.Azure.WebJobs 2.2.0 && < 2.3.0 if you're building against .NET Framework 4.6 instead of .NET Standard. (https://www.nuget.org/packages/Microsoft.NET.Sdk.Functions/1.0.12)

If you run ```func```  on your host, what version of the Azure Core tools and Runtime do you see? 
Mine is:
Azure Functions Core Tools (2.0.1-beta.23)
Function Runtime Version: 2.0.11587.0

**Comment by keesschollaart81** [comment]
I'm guessing this has been solved by now. Feel free to comment then we'll see how we can fix this!
